type Book @model {
  id: ID
  MediaTypeId: Int
  TakenDateTime: String
  CategoryTags: String
  MenuTags: String
  AlbumTags: String
  Title: String
  Description: String
  People: String
  ToBeProcessed: Boolean
}
