type Book @model {
  id: ID
  MediaTypeId: Int
  TakenDateTime: String
  CategoryTags: String
  MenuTags: String
  AlbumTags: String
  Title: String
  Description: String
  People: String
  ToBeProcessed: Boolean
}

type Mtype @model {
  id: ID
  MediaTypeId: Int
  MediaTypeDesc: String
  Category: [CategoryType]
}

type CategoryType {
  CategoryName: String
  Menu: [MenuType]
}

type MenuType {
  MenuItem: String
}
